#!/bin/bash
# Setup Auto Sync - Configure automated daily syncs via cron

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
BLUE='\033[0;34m'
YELLOW='\033[1;33m'
CYAN='\033[0;36m'
NC='\033[0m'

print_header() {
    echo -e "${BLUE}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
    echo -e "${BLUE}  Setup Automated Sync${NC}"
    echo -e "${BLUE}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
    echo ""
}

check_credentials() {
    if [ ! -f ~/.garmin-coach-credentials.enc ]; then
        echo -e "${RED}✗${NC} Encrypted credentials not found"
        echo ""
        echo "Setup credentials first:"
        echo "  $SCRIPT_DIR/credential-manager.sh save"
        echo ""
        return 1
    fi
    
    echo -e "${GREEN}✓${NC} Encrypted credentials found"
    return 0
}

create_cron_script() {
    local cron_script="$PROJECT_ROOT/data/.auto-sync-cron.sh"
    
    cat > "$cron_script" <<'EOF'
#!/bin/bash
# Auto-sync cron job - DO NOT EDIT MANUALLY
# Generated by setup-auto-sync.sh

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/../scripts" && pwd)"
export AUTO_MODE=true
export PROFILE_ID="${PROFILE_ID:-test-athlete-1}"

# Run sync manager
"$SCRIPT_DIR/sync-manager.sh" >> "$SCRIPT_DIR/../data/logs/auto-sync.log" 2>&1
EOF
    
    chmod +x "$cron_script"
    echo "$cron_script"
}

setup_cron_macos() {
    local sync_time="$1"
    local cron_script="$2"
    
    # Parse time (format: HH:MM)
    local hour="${sync_time%:*}"
    local minute="${sync_time#*:}"
    
    # Create cron entry
    local cron_entry="$minute $hour * * * $cron_script"
    
    # Check if entry already exists
    if crontab -l 2>/dev/null | grep -q "$cron_script"; then
        echo -e "${YELLOW}⚠${NC}  Cron job already exists. Updating..."
        crontab -l 2>/dev/null | grep -v "$cron_script" | crontab -
    fi
    
    # Add new entry
    (crontab -l 2>/dev/null; echo "$cron_entry") | crontab -
    
    echo -e "${GREEN}✓${NC} Cron job added: Daily at $sync_time"
    echo ""
    echo "Note: On macOS, you may need to grant Terminal full disk access:"
    echo "  Settings → Privacy & Security → Full Disk Access → Terminal"
    echo ""
}

setup_launchd_macos() {
    local sync_time="$1"
    local plist_file="$HOME/Library/LaunchAgents/com.garmin-coach.auto-sync.plist"
    
    # Parse time
    local hour="${sync_time%:*}"
    local minute="${sync_time#*:}"
    
    # Create plist
    cat > "$plist_file" <<EOF
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
    <key>Label</key>
    <string>com.garmin-coach.auto-sync</string>
    
    <key>ProgramArguments</key>
    <array>
        <string>$SCRIPT_DIR/sync-manager.sh</string>
    </array>
    
    <key>EnvironmentVariables</key>
    <dict>
        <key>AUTO_MODE</key>
        <string>true</string>
        <key>PROFILE_ID</key>
        <string>${PROFILE_ID:-test-athlete-1}</string>
        <key>PATH</key>
        <string>/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin</string>
    </dict>
    
    <key>StartCalendarInterval</key>
    <dict>
        <key>Hour</key>
        <integer>$hour</integer>
        <key>Minute</key>
        <integer>$minute</integer>
    </dict>
    
    <key>StandardOutPath</key>
    <string>$PROJECT_ROOT/data/logs/auto-sync.log</string>
    
    <key>StandardErrorPath</key>
    <string>$PROJECT_ROOT/data/logs/auto-sync-error.log</string>
    
    <key>RunAtLoad</key>
    <false/>
</dict>
</plist>
EOF
    
    # Load the plist
    launchctl unload "$plist_file" 2>/dev/null || true
    launchctl load "$plist_file"
    
    echo -e "${GREEN}✓${NC} LaunchAgent created: Daily at $sync_time"
    echo ""
    echo "LaunchAgent file: $plist_file"
    echo ""
    echo "Manage with launchctl:"
    echo "  launchctl unload $plist_file  # Disable"
    echo "  launchctl load $plist_file    # Enable"
    echo ""
}

show_menu() {
    echo "Choose automation method:"
    echo ""
    echo "  1) cron (traditional Unix scheduling)"
    echo "  2) launchd (macOS LaunchAgent, recommended)"
    echo "  3) manual (instructions only)"
    echo "  4) cancel"
    echo ""
    read -p "Select option [1-4]: " choice
    
    case "$choice" in
        1|2|3) echo "$choice" ;;
        4) exit 0 ;;
        *) echo "1" ;;  # Default to cron
    esac
}

get_sync_time() {
    echo ""
    echo "When should the daily sync run?"
    echo ""
    read -p "Enter time (HH:MM, 24-hour format) [default: 06:00]: " sync_time
    
    if [ -z "$sync_time" ]; then
        echo "06:00"
        return
    fi
    
    # Validate format
    if ! echo "$sync_time" | grep -qE '^[0-2][0-9]:[0-5][0-9]$'; then
        echo -e "${YELLOW}⚠${NC}  Invalid format. Using default: 06:00"
        echo "06:00"
        return
    fi
    
    echo "$sync_time"
}

show_manual_instructions() {
    echo "Manual Setup Instructions:"
    echo ""
    echo "To run sync manually at any time:"
    echo "  $SCRIPT_DIR/sync-manager.sh"
    echo ""
    echo "For automated scheduling, add this to your crontab:"
    echo "  # Garmin AI Coach daily sync at 6:00 AM"
    echo "  0 6 * * * cd $PROJECT_ROOT && $SCRIPT_DIR/sync-manager.sh"
    echo ""
    echo "Edit crontab:"
    echo "  crontab -e"
    echo ""
}

test_sync() {
    echo -e "${CYAN}🧪${NC} Testing sync process..."
    echo ""
    
    if ! check_credentials; then
        return 1
    fi
    
    read -p "Run a test sync now? (y/n) [n]: " run_test
    
    if [[ "$run_test" =~ ^[Yy]$ ]]; then
        echo ""
        "$SCRIPT_DIR/sync-manager.sh"
    else
        echo ""
        echo "Test skipped. Run manually when ready:"
        echo "  $SCRIPT_DIR/sync-manager.sh"
        echo ""
    fi
}

main() {
    print_header
    
    if ! check_credentials; then
        exit 1
    fi
    
    local method=$(show_menu)
    
    case "$method" in
        1)
            local sync_time=$(get_sync_time)
            local cron_script=$(create_cron_script)
            setup_cron_macos "$sync_time" "$cron_script"
            ;;
        2)
            local sync_time=$(get_sync_time)
            setup_launchd_macos "$sync_time"
            ;;
        3)
            show_manual_instructions
            ;;
    esac
    
    echo "Setup complete!"
    echo ""
    echo "Check sync status anytime:"
    echo "  $SCRIPT_DIR/sync-status.sh"
    echo ""
    
    test_sync
}

main "$@"
